# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12cSG1Tnq0l0NP7p9gqHDgGcXTtsEtckY
"""

!pip install openneuro-py nilearn nibabel scikit-learn pandas matplotlib

from openneuro import download

download(dataset="ds000003", target_dir="openneuro_data")

import os

mri_file = None

for root, dirs, files in os.walk("openneuro_data"):
    for file in files:
        if file.endswith(".nii") or file.endswith(".nii.gz"):
            mri_file = os.path.join(root, file)
            break
    if mri_file:
        break

print("MRI file found:", mri_file)

import nibabel as nib

img = nib.load(mri_file)

print("MRI shape:", img.shape)

import numpy as np

data = img.get_fdata()

X = data.reshape(-1, data.shape[-1])

print(X.shape)

from sklearn.cluster import KMeans

sample = X[:5000]

kmeans = KMeans(n_clusters=3)

kmeans.fit(sample)

labels = kmeans.labels_

print(labels[:10])

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

pca = PCA(n_components=2)

X_reduced = pca.fit_transform(sample)

plt.scatter(X_reduced[:,0], X_reduced[:,1], c=labels, s=5)

plt.title("Brain Activity Clusters")

plt.show()